logging:
  mode: offline
  project: cellvit++
  log_comment: cellvit++
  wandb_dir: /workspace/CellViT-plus-plus/cellvit/logs_local/wandb
  log_dir: /workspace/CellViT-plus-plus/cellvit/logs_local/2025-07-28T041658_cellvit++
  level: Info
  notes: cellvit++
  run_id: twei9mmh
  wandb_file: twei9mmh
random_seed: 19
gpu: 0
data:
  dataset: segmentationdataset
  dataset_path: ./dataset/transformed/CoNSeP
  train_filelist: ./dataset/transformed/CoNSeP/splits/fold_0/train.csv
  val_filelist: ./dataset/transformed/CoNSeP/splits/fold_0/val.csv
  normalize_stains_train: false
  normalize_stains_val: false
  label_map:
    0: Other
    1: Inflammatory
    2: Healthy Epithelial
    3: Dysplastic/Malignant epithelial
    4: Fibroblast
    5: Muscle
    6: Endothelial
  num_classes: 7
cellvit_path: ../checkpoints/CellViT-SAM-H-x40-AMP.pth
model:
  hidden_dim: 128
training:
  cache_cell_dataset: true
  batch_size: 256
  epochs: 50
  drop_rate: 0.1
  optimizer: AdamW
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.9
    lr: 0.0005
    weight_decay: 0.0005
  early_stopping_patience: 20
  scheduler:
    scheduler_type: constant
  mixed_precision: true
  eval_every: 1
run_sweep: false
agent: null
just_load_model: false
